### ISSUE TITLE
Result's in table 1 of the paper

### ISSUE THREAD

**Issue by Zhengyang1995** [KAIST-vilab/OC-CSE#3]
Hey, thank you for your impressive work.
I just want to make sure for the result ‘56.0’ in the table 1 of the paper.
Is it the performance without PSA method?
Thanks a lot~

**Comment by sunghoonYoon** [comment]
Yes, the 56.0 (%) is the mIoU of seed(CAMs without CRF) itself. 
The performance of pseudo labels (with PSA) achieve 66.9% mIoU on PASCAL VOC 2012 train set.
