### ISSUE TITLE
Cannot reproduce your result

### ISSUE THREAD

**Issue by oooooppppsk** [KAIST-vilab/OC-CSE#6]
Hi, thanks for your great work.
I have trained your code for several times, but the best result of CAM is 55.05, which is lower than your reported result (56.0). I haven't changed any code in this repo. Can you provide some insights?

**Comment by yoon307** [comment]
Sorry for the late response. Since we successively reproduced our results on several different machines, 
I personally recommend you to change the seed (torch,numpy and etc).
